version: "3"
services:
  api:
    build: ./api
    volumes:
      - .:/api # 현재 디렉토리를 컨테이너의 /app에 마운트
    ports:
      - "8000:8000" # 호스트의 8000 포트를 컨테이너의 8000 포트에 매핑
    environment:
      - PYTHONUNBUFFERED=1 # 로그 출력을 즉시 보여주기 위한 환경 변수

  front: # 새로운 데이터베이스 서비스 추가
    build: ./front
    volumes:
      - .:/front # 현재 디렉토리를 컨테이너의 /front에 마운트
    ports:
      - "3000:3000" # 호스트의 8000 포트를 컨테이너의 3000 포트에 매핑
